/** Screenshots of the main screens for the README (needs `npx vite preview` on :4174). */
import { chromium, devices } from '@playwright/test';
const out = process.env.OUT ?? 'docs/shots';
const base = 'http://localhost:4174/boundless-ops/';
const browser = await chromium.launch();
const ctx = await browser.newContext({ ...devices['iPhone 13'] });
const page = await ctx.newPage();
await page.clock.install({ time: new Date('2026-09-23T15:00:00-07:00') });
await page.goto(base + '#/kit');
await page.waitForFunction(() => !!(window as unknown as { __bops?: unknown }).__bops);
await page.evaluate(async () => { const h = (window as any).__bops; await h.updateSettings({ age: 30, silentSwitchWarned: true }); await h.startBlock('2026-09-21'); });
await page.goto(base + '#/today');
await page.waitForSelector('[data-testid="today"]');
await page.screenshot({ path: `${out}/01-today.png`, fullPage: true });
await page.goto(base + '#/schedule');
await page.waitForSelector('[data-testid="day-1"]');
await page.screenshot({ path: `${out}/02-schedule.png`, fullPage: true });
await page.goto(base + '#/library');
await page.waitForSelector('[data-testid="library"]');
await page.screenshot({ path: `${out}/03-library.png`, fullPage: false });
await page.goto(base + '#/session/A?day=3&slot=main&variant=kbSwings');
await page.waitForSelector('[data-testid="timer"]');
await page.screenshot({ path: `${out}/04-session-setup.png`, fullPage: true });
await page.getByTestId('start').click();
await page.clock.runFor(10_000 + 20_000 + 2_000);
await page.screenshot({ path: `${out}/05-timer-rest.png`, fullPage: false });
await page.goto(base + '#/kit');
await page.waitForSelector('[data-testid="kit"]');
await page.screenshot({ path: `${out}/06-kit.png`, fullPage: true });
await browser.close();
console.log('done');
